version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands: 
      - cd MyWork/Week6/card-app-redux-with-test
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'MyWork/Week6/card-app-redux-with-test'