version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands: 
      - cd Rev/MyWork/Week6/card-app-redux with test
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'Rev/MyWork/Week6/card-app-redux with test'